name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.0, v1.1.0
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore MicroJpeg.sln

      - name: Build
        run: dotnet build MicroJpeg.sln -c Release --no-restore

      - name: Test
        run: dotnet test MicroJpeg.sln -c Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack src/MicroJpeg/MicroJpeg.csproj -c Release --no-build -o out

      - name: Push to GitHub Packages
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
